config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
    patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get 'books/:id' => 'books#show', as: 'book'


root to: 'books#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def top


  end

  def index
  	@book = Book.new
  	@books = Book.all
  end

  def create
	book = Book.new(book_params)
    if book.save
     	flash[:notice] = "Book was successfully created."
        redirect_to book_path(book.id)

	end
  end

    def show
    	 @book = Book.find(params[:id])
    end

    def edit
         @book = Book.find(params[:id])
    end

    def update
        book = Book.find(params[:id])
        if book.update(book_params)
        	flash[:notice] = "Book was successfully updated."
            redirect_to book_path(book.id)
        end
    end

    def destroy
    	book = Book.find(params[:id])
        if book.destroy
        	flash[:notice] = "Book was successfully destroyed."
            redirect_to books_path
        end
    end

  private
    def book_params
        params.require(:book).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
      <% end %>

    <div>
    	<h1>Editing Book</h1>
	<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>

   <%= link_to "Show", book_path(@book.id) %>
   <%= link_to "Back", books_path %>


</body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>kadai2</title>
</head>
<body>

<h1>Books</h1>
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
      <% end %>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
			<th colspan="3"></th>

		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
            <td><%=book.title %></td>
            <td><%=book.body %></td>
            <td><%= link_to "Show", book_path(book.id) %></td>
            <td><%= link_to "Edit", edit_book_path(book.id) %></td>
            <td><%= link_to "Destroy", destroy_book_path(book.id), method: :'delete' %>
            </td>

		</tr>
		<% end %>

		
	</tbody>
</table>

<div>
<%= form_for(@book) do |f| %>

<h2>New book</h2>

<h4>Title</h4>
    <%= f.text_field :title %>
 
    <h4>Body</h4>
    <%= f.text_area :body %>
 
    <div>
    	<%= f.submit 'Creat Book' %>
    </div>

<% end %>
</div>
</body>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<div class="ss">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

 <p><strong>Title:</strong>
	<%= @book.title %></p>
 <p><strong>Body:</strong>
	<%= @book.body %></p>
</div>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>



</body>
</html>

app/views/books/top.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<h1 class="aa">ようこそ　Bookerへ！</h1>
<div>
<P>Bookers では、さまざまな書籍に関するあなたの意見や</P>
<p>印象を共有し交換することができます</p>
</div>
<%= link_to "Start", books_path %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>